def generate_report(
    overall_score,
    ats_score,
    skill_score,
    semantic_score,
    matched_skills,
    missing_skills,
    required_missing,
    preferred_missing,
    recommendations,
    resume_suggestions,
    ats_suggestions
):

    report = []

    report.append("CAREERMATCH AI - RESUME ANALYSIS REPORT")
    report.append("=" * 50)
    report.append("")

    # --------------------------------------------------
    # Score Summary
    # --------------------------------------------------

    report.append("SCORE SUMMARY")
    report.append("-" * 30)

    report.append(
        f"Overall Match Score: {overall_score:.1f}%"
    )

    report.append(
        f"ATS Score: {ats_score:.1f}%"
    )

    report.append(
        f"Skill Match: {skill_score:.1f}%"
    )

    report.append(
        f"Semantic Similarity: {semantic_score:.1f}%"
    )

    report.append("")


    # --------------------------------------------------
    # Matching Skills
    # --------------------------------------------------

    report.append("MATCHING SKILLS")
    report.append("-" * 30)

    if matched_skills:

        for skill in sorted(matched_skills):

            report.append(
                f"- {skill}"
            )

    else:

        report.append(
            "No matching skills found."
        )

    report.append("")


    # --------------------------------------------------
    # Missing Skills
    # --------------------------------------------------

    report.append("MISSING SKILLS")
    report.append("-" * 30)

    if missing_skills:

        for skill in sorted(missing_skills):

            report.append(
                f"- {skill}"
            )

    else:

        report.append(
            "No major missing skills detected."
        )

    report.append("")


    # --------------------------------------------------
    # Required Skill Gaps
    # --------------------------------------------------

    report.append("REQUIRED SKILL GAPS")
    report.append("-" * 30)

    if required_missing:

        for skill in sorted(required_missing):

            report.append(
                f"- {skill}"
            )

    else:

        report.append(
            "No required skill gaps detected."
        )

    report.append("")


    # --------------------------------------------------
    # Preferred Skill Gaps
    # --------------------------------------------------

    report.append("PREFERRED SKILL GAPS")
    report.append("-" * 30)

    if preferred_missing:

        for skill in sorted(preferred_missing):

            report.append(
                f"- {skill}"
            )

    else:

        report.append(
            "No preferred skill gaps detected."
        )

    report.append("")


    # --------------------------------------------------
    # Skill Gap Recommendations
    # --------------------------------------------------

    report.append("SKILL GAP RECOMMENDATIONS")
    report.append("-" * 30)

    if recommendations:

        for recommendation in recommendations:

            report.append(
                f"- {recommendation}"
            )

    else:

        report.append(
            "No additional recommendations."
        )

    report.append("")


    # --------------------------------------------------
    # Resume Improvement Suggestions
    # --------------------------------------------------

    report.append("RESUME IMPROVEMENT SUGGESTIONS")
    report.append("-" * 30)

    if resume_suggestions:

        for suggestion in resume_suggestions:

            report.append(
                f"- {suggestion}"
            )

    else:

        report.append(
            "No improvement suggestions available."
        )

    report.append("")


    # --------------------------------------------------
    # ATS Suggestions
    # --------------------------------------------------

    report.append("ATS IMPROVEMENT SUGGESTIONS")
    report.append("-" * 30)

    if ats_suggestions:

        for suggestion in ats_suggestions:

            report.append(
                f"- {suggestion}"
            )

    else:

        report.append(
            "No ATS improvement suggestions."
        )

    report.append("")


    # --------------------------------------------------
    # Report Footer
    # --------------------------------------------------

    report.append("=" * 50)
    report.append(
        "Generated by CareerMatch AI"
    )

    return "\n".join(report)